### ISSUE TITLE
x vs laggedx as independent variable in vignette plot

### ISSUE THREAD

**Issue by andrewletten** [adamtclark/gauseR#2]
Great resource Adam!

On line 45 of the vignette (gauseR_examples.Rmd), should the independent variable not be `laggedx` (or alternatively `midx`) rather than `x`?

**Comment by adamtclark** [comment]
Thanks! And yep -- good catch. I've updated the code to use laggedx.

**Comment by adamtclark** [comment]
Committed fix.
